### ISSUE TITLE
Allure combine index.html does not exists

### ISSUE THREAD

**Issue by falukky** [MihanEntalpo/allure-single-html-file#20]
So in my project I have this reports directory when all .json files generated and at the end I can use the command allure serve .\reports\ and see my HTML report file. After quick search I found allure-combine module that creates single HTML file builder and after my tests finished I try to run the command allure-combine .\reports\ but got this error:

Exception: ERROR: File .\reports\index.html doesn't exists, but it should!

According allure-combine I should use this command:
allure-combine ./some/path/to/allure/generated/folder

So in my case it should be allure-combine .\reports

This index.html does not exist in my folder - What I am doing wrong ?

**Comment by MihanEntalpo** [comment]
@falukky hello. Please, provide your allure report folder compressed, and also the command on which you've generator report

**Comment by falukky** [comment]
Where allure report folder located ?

**Comment by falukky** [comment]
Currently this is my error:

 Folder to process is .\reports
> Checking for folder contents
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myuser\PycharmProjects\automation\venv\Scripts\allure-combine.exe\__main__.py", line 7, in <module>
  File "C:\Users\myuser\PycharmProjects\automation\venv\lib\site-packages\allure_combine\combine.py", line 302, in main
    combine_allure(args.folder.rstrip(sep), args.dest, args.remove_temp_files, args.auto_create_folders, args.ignore_utf8_errors)
  File "C:\Users\myuser\PycharmProjects\automation\venv\lib\site-packages\allure_combine\combine.py", line 60, in combine_allure
    raise Exception(f"ERROR: File {folder + sep + file} doesnt exists, but it should!")
(venv) PS C:\Users\myuser\PycharmProjects\automation> pip freeze > requirements.txt
(venv) PS C:\Users\myuser\PycharmProjects\automation> allure-combine .\reports\                                                                                         
> Folder to process is .\reports
> Checking for folder contents                                                                                                   
Traceback (most recent call last):                                                                                               
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main                                                
    return _run_code(code, main_globals, None,                                                                                   
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code                                                           
    exec(code, run_globals)                                                                                                      
  File "C:\Users\myuser\PycharmProjects\automation\venv\Scripts\allure-combine.exe\__main__.py", line 7, in <module>             
  File "C:\Users\myuser\PycharmProjects\automation\venv\lib\site-packages\allure_combine\combine.py", line 302, in main          
    combine_allure(args.folder.rstrip(sep), args.dest, args.remove_temp_files, args.auto_create_folders, args.ignore_utf8_errors)
  File "C:\Users\myuser\PycharmProjects\automation\venv\lib\site-packages\allure_combine\combine.py", line 60, in combine_allure
    raise Exception(f"ERROR: File {folder + sep + file} doesnt exists, but it should!")
Exception: ERROR: File .\reports\index.html doesnt exists, but it should!

Generate report command: pytest -v -s --address 1.2.3.3 --alluredir=.\reports .\tests\commands\change.py -m sanity -v

Command: C:\Users\myuser\PycharmProjects\automation> allure-combine .\reports\

**Comment by MihanEntalpo** [comment]
Folder where allure generate its report, the path should be displayed in the output of allure generation process

**Comment by MihanEntalpo** [comment]
When you call allure serve, folder with index.html should be generated somewhere in your project or temporary folders

**Comment by falukky** [comment]
My allure report is open now and no HTML file in my project

**Comment by falukky** [comment]
Ok I found this temp folder with index.tml file, what now ?

**Comment by MihanEntalpo** [comment]
Specify this temp folder as an argument to allure-combine command, and "complete.html" file would be created inside. This file is what you need.

**Comment by MihanEntalpo** [comment]
It seems, that everything is ok, so if you have some details, feel free to reopen this issue
